name: Test
on:
  push:

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: setup
      run: curl -L https://git.io/fjaxx | repo=ysmood/kit bin=godev ver=v0.22.2 sh
 
    - name: test
      run: godev -l -m 100

    - uses: codecov/codecov-action@v1
